### ISSUE TITLE
做一个简单的 RequestBodyBuilder 实现， 比如直接对参数 转json 转xml 等

### ISSUE THREAD

**Issue by ijiangtao** [venusdrogon/feilong-platform#228]
做一个简单的 RequestBodyBuilder 实现， 比如直接对参数 转json 转xml 等

![image](https://user-images.githubusercontent.com/28173035/43198292-b7167746-9040-11e8-80bc-4563f7829042.png)

**Comment by venusdrogon** [comment]
![image](https://user-images.githubusercontent.com/3479472/43277485-c585a1f8-913a-11e8-8d6b-b342a98ab08c.png)

```XML
<property name="requestBodyBuilder">
		<!-- <bean class="com.baozun.store.order.RoutingRequestBodyBuilder" /> -->
	<bean class="com.feilong.context.invoker.http.SimpleJsonRequestBodyBuilder" />
</property>
```


测试效果 


![image](https://user-images.githubusercontent.com/3479472/43277676-50643ea6-913b-11e8-86b7-8090fe5f9c64.png)

**Comment by venusdrogon** [comment]
xml 格式的再说, 暂时没有测试场景
