### ISSUE TITLE
stringFormatter 支持 字符串配置， 而不是配置一个类

### ISSUE THREAD

**Issue by ijiangtao** [venusdrogon/feilong-platform#229]
stringFormatter 支持 字符串配置， 而不是配置一个类

![image](https://user-images.githubusercontent.com/28173035/43198524-8da16b86-9041-11e8-9bf6-7472fea9ad34.png)

**Comment by venusdrogon** [comment]
关联 #230

**Comment by venusdrogon** [comment]
![image](https://user-images.githubusercontent.com/3479472/76497425-eab67a00-6475-11ea-9a47-5a9c70fa5760.png)


![image](https://user-images.githubusercontent.com/3479472/76497620-513b9800-6476-11ea-89c7-4913e1494dc9.png)

**Comment by venusdrogon** [comment]
![image](https://user-images.githubusercontent.com/3479472/76498667-4c77e380-6478-11ea-86bf-41a67f187782.png)
