### ISSUE TITLE
HttpMethodType增加Put

### ISSUE THREAD

**Issue by ijiangtao** [venusdrogon/feilong-platform#231]
![image](https://user-images.githubusercontent.com/28173035/43398667-60eb9280-943b-11e8-81b1-c4f5b86e093f.png)

**Comment by ijiangtao** [comment]
![image](https://user-images.githubusercontent.com/28173035/43399116-957cb636-943c-11e8-9426-bef833d60266.png)

**Comment by venusdrogon** [comment]
see https://github.com/venusdrogon/feilong-net/issues/31

**Comment by venusdrogon** [comment]
移动到 see venusdrogon/feilong-net#31
