### ISSUE TITLE
引入feilong-velocity报错

### ISSUE THREAD

**Issue by RussiaVk** [venusdrogon/feilong-platform#367]
`		<dependency>
			<groupId>com.feilong.platform</groupId>
			<artifactId>feilong-velocity</artifactId>
			<version>${version.feilong-platform}</version>
		</dependency>`

**Comment by venusdrogon** [comment]
新版本的 feilong-velocity 已经不在独立deploy 了 

仓库中  feilong-velocity 版本到 1.11.1   https://github.com/venusdrogon/feilong-platform/tree/repository/com/feilong/platform/feilong-velocity

![image](https://user-images.githubusercontent.com/3479472/76483634-7fa77c00-6452-11ea-9946-46016b6af0ba.png)


推荐直接使用 feilong 全家桶 ,里面包含了 feilong-velocity 所有的功能

```XML
<dependency> 
<groupId>com.feilong.platform</groupId> 
<artifactId>feilong-util-all</artifactId> 
<version>${version.feilong-platform}</version> 
</dependency>
```

**Comment by RussiaVk** [comment]
> 新版本的 feilong-velocity 已经不在独立deploy 了
> 
> 仓库中 feilong-velocity 版本到 1.11.1 https://github.com/venusdrogon/feilong-platform/tree/repository/com/feilong/platform/feilong-velocity
> 
> ![image](https://user-images.githubusercontent.com/3479472/76483634-7fa77c00-6452-11ea-9946-46016b6af0ba.png)
> 
> 推荐直接使用 feilong 全家桶 ,里面包含了 feilong-velocity 所有的功能
> 
> ```
> <dependency> 
> <groupId>com.feilong.platform</groupId> 
> <artifactId>feilong-util-all</artifactId> 
> <version>${version.feilong-platform}</version> 
> </dependency>
> ```
谢谢，那算了吧，本来想单独引入的
