### ISSUE TITLE
pom.xml导入不了！！！最高只能导入2.0.2

### ISSUE THREAD

**Issue by RussiaVk** [venusdrogon/feilong-platform#389]
![image](https://user-images.githubusercontent.com/43515485/83385664-35fc7b00-a41c-11ea-89a0-2464348ad0b9.png)
![image](https://user-images.githubusercontent.com/43515485/83385703-4876b480-a41c-11ea-8597-77586ec10a3c.png)

**Comment by venusdrogon** [comment]
最近有用户反馈下载不到 2.1.0  ,但确认 jar 已经在仓库里了, 可以查看 https://github.com/venusdrogon/feilong-platform/tree/repository/com/feilong/platform/feilong-core/2.1.0

![image](https://user-images.githubusercontent.com/3479472/84998812-e9869e80-b182-11ea-830c-050e0b027887.png)

结果分析, 查看到华为云bbs  https://bbs.huaweicloud.com/blogs/143682  ,原因在于 "由于某些你懂的因素，导致GitHub的raw.githubusercontent.com域名解析被污染了。"

你可以按照 这个bbs 的方案 设置 host 来解决问题

同时作为feilong作者, 建议使用 feilong 3版本  https://github.com/ifeilong/feilong , 

**有以下的亮点:**

- deploy到 maven中央仓库
- aliyun 镜像可更新
- 兼容 feilong-core 2.1.0
- 基于JDK8
- 0 依赖其他jar
